/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as PublicSearchRouteImport } from './routes/_public/search'
import { Route as AdminArticlesRouteRouteImport } from './routes/admin/articles/route'
import { Route as AdminArticlesIndexRouteImport } from './routes/admin/articles/index'
import { Route as PublicKategoriSlugRouteImport } from './routes/_public/kategori/$slug'
import { Route as PublicArtikelSlugRouteImport } from './routes/_public/artikel/$slug'
import { Route as AdminArticlesArticleIdRouteRouteImport } from './routes/admin/articles/$articleId/route'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const PublicSearchRoute = PublicSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PublicRoute,
} as any)
const AdminArticlesRouteRoute = AdminArticlesRouteRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesIndexRoute = AdminArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminArticlesRouteRoute,
} as any)
const PublicKategoriSlugRoute = PublicKategoriSlugRouteImport.update({
  id: '/kategori/$slug',
  path: '/kategori/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicArtikelSlugRoute = PublicArtikelSlugRouteImport.update({
  id: '/artikel/$slug',
  path: '/artikel/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const AdminArticlesArticleIdRouteRoute =
  AdminArticlesArticleIdRouteRouteImport.update({
    id: '/$articleId',
    path: '/$articleId',
    getParentRoute: () => AdminArticlesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/articles': typeof AdminArticlesRouteRouteWithChildren
  '/search': typeof PublicSearchRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/articles/$articleId': typeof AdminArticlesArticleIdRouteRoute
  '/artikel/$slug': typeof PublicArtikelSlugRoute
  '/kategori/$slug': typeof PublicKategoriSlugRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/search': typeof PublicSearchRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/articles/$articleId': typeof AdminArticlesArticleIdRouteRoute
  '/artikel/$slug': typeof PublicArtikelSlugRoute
  '/kategori/$slug': typeof PublicKategoriSlugRoute
  '/admin/articles': typeof AdminArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin/articles': typeof AdminArticlesRouteRouteWithChildren
  '/_public/search': typeof PublicSearchRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/articles/$articleId': typeof AdminArticlesArticleIdRouteRoute
  '/_public/artikel/$slug': typeof PublicArtikelSlugRoute
  '/_public/kategori/$slug': typeof PublicKategoriSlugRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/articles'
    | '/search'
    | '/admin/categories'
    | '/admin/login'
    | '/admin/'
    | '/admin/articles/$articleId'
    | '/artikel/$slug'
    | '/kategori/$slug'
    | '/admin/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/search'
    | '/admin/categories'
    | '/admin/login'
    | '/'
    | '/admin'
    | '/admin/articles/$articleId'
    | '/artikel/$slug'
    | '/kategori/$slug'
    | '/admin/articles'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/admin/articles'
    | '/_public/search'
    | '/admin/categories'
    | '/admin/login'
    | '/_public/'
    | '/admin/'
    | '/admin/articles/$articleId'
    | '/_public/artikel/$slug'
    | '/_public/kategori/$slug'
    | '/admin/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/search': {
      id: '/_public/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PublicSearchRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/': {
      id: '/admin/articles/'
      path: '/'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminArticlesIndexRouteImport
      parentRoute: typeof AdminArticlesRouteRoute
    }
    '/_public/kategori/$slug': {
      id: '/_public/kategori/$slug'
      path: '/kategori/$slug'
      fullPath: '/kategori/$slug'
      preLoaderRoute: typeof PublicKategoriSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/artikel/$slug': {
      id: '/_public/artikel/$slug'
      path: '/artikel/$slug'
      fullPath: '/artikel/$slug'
      preLoaderRoute: typeof PublicArtikelSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/articles/$articleId': {
      id: '/admin/articles/$articleId'
      path: '/$articleId'
      fullPath: '/admin/articles/$articleId'
      preLoaderRoute: typeof AdminArticlesArticleIdRouteRouteImport
      parentRoute: typeof AdminArticlesRouteRoute
    }
  }
}

interface PublicRouteChildren {
  PublicSearchRoute: typeof PublicSearchRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicArtikelSlugRoute: typeof PublicArtikelSlugRoute
  PublicKategoriSlugRoute: typeof PublicKategoriSlugRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicSearchRoute: PublicSearchRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicArtikelSlugRoute: PublicArtikelSlugRoute,
  PublicKategoriSlugRoute: PublicKategoriSlugRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminArticlesRouteRouteChildren {
  AdminArticlesArticleIdRouteRoute: typeof AdminArticlesArticleIdRouteRoute
  AdminArticlesIndexRoute: typeof AdminArticlesIndexRoute
}

const AdminArticlesRouteRouteChildren: AdminArticlesRouteRouteChildren = {
  AdminArticlesArticleIdRouteRoute: AdminArticlesArticleIdRouteRoute,
  AdminArticlesIndexRoute: AdminArticlesIndexRoute,
}

const AdminArticlesRouteRouteWithChildren =
  AdminArticlesRouteRoute._addFileChildren(AdminArticlesRouteRouteChildren)

interface AdminRouteChildren {
  AdminArticlesRouteRoute: typeof AdminArticlesRouteRouteWithChildren
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArticlesRouteRoute: AdminArticlesRouteRouteWithChildren,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
